### PR TITLE
Added ruby-2.3.3 as the version required

### PR DESCRIPTION
**Pull request by emad-elsaid**
2.2.x doesn't work because we are using the safe navigation operator
and 2.4.x won't work because the json gem has some problems on mac with
this version, even updating the gems won't work because some code needs
migration, so this ruby version is the latest version we can use so far.

### CODE REVIEW

**Comment by larspetrus** [comment]
I hadn't seen `.ruby-version` before, but after investigating I like it a lot. Thanks!

**Comment by emad-elsaid** [comment]
You're welcome, I figured out we need it in this project as it needs a specific version to start it.

Also it'll be a nice thing to have seeds.rb file to seed the database with some data for contributors.

**Comment by larspetrus** [comment]
Yeah, I've thought about that. It's probably fairly useless right now if you're not on my machine :) .

The full DB is way too big to fit here, and also not entirely mine. But I'll figure out decent subset, hopefully soon.

**Comment by larspetrus** [comment]
`rake db:seed` should now produce a decent DB with algs for all positions and a bunch of combo algs. Let me know if it works!

**Comment by emad-elsaid** [comment]
I tried to `rake db:seed` now from master and it couldn't find that file `Birdflu/seed_data/positions.csv`

**Comment by larspetrus** [comment]
Well that's embarrassing... I just didn't add them to git! My IDE usually handles that, so I've grown sloppy.

Sorry about that. The files are there now!

**Comment by emad-elsaid** [comment]
it worked, WOW this is beautiful, opening it locally with these 4000+ algs feels impressive,
I'll try to enhance the frontend a little bit, maybe add a good css framework or so.

**Comment by larspetrus** [comment]
I've started looking at some CSS frameworks, but I don't know much about that world.

I'd definitely want to upgrade my clunky homegrown/borrowed buttons and drop downs.

**Pull request merged**
